# These pre-commit hooks don't ensure a passing CI run. Instead they act as
# a quick "smoke check" running static code analysis on the files changed.
# The hooks do NOT:
#     - Run tests or other time-consuming tasks.
#     - Check the whole codebase, just modified files.
#     - Let mypy access dependencies' typehints.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
  - id: mypy
    # Add args that suppress errors resulting from no access to dependencies
    args: [--ignore-missing-imports, --no-warn-unused-ignores, --scripts-are-modules]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear>=19.3.0,<20
    - flake8-import-order>=0.18.1,<0.19
    - flake8-builtins>=1.4.1,<2